### ISSUE TITLE
calculate_cosin函数

### ISSUE THREAD

**Issue by ACXuLiu** [hackerxiaobai/OpenTag_2019#2]
Hello， 非常感谢作者的分享。我阅读您的代码，发现OpenTag模型里面并没有用到attention layer吧？我只看到了calculate_cosin这个函数，计算context和att的的距离。故而想向您确认下，模型是否用到了attention layer呢？

**Comment by hackerxiaobai** [comment]
你好，你可以在仔细阅读一下这个函数哟calculate_cosin。cos计算本身就是一个很好的attention计算啊。

**Comment by ACXuLiu** [comment]
哈哈，十分感谢您的指点。
        现在有个问题想向您请教下，我看程序最终可以将测试文本的序列标注出来，但是无法判断标出来的文本是哪种属性，针对这种情况，是不是需要从数据入手，针对每个属性构造一批数据，训练一个model呢？
         我刚入门NLP, 导师最近给了一个商品属性提取的课题，万望解惑，感激不尽🤣

**Comment by hackerxiaobai** [comment]
你可以在接一个分类模型或许
