### ISSUE TITLE
Is the dataset used in this project the same as the dataset used in the paper?

### ISSUE THREAD

**Issue by w-zm** [hackerxiaobai/OpenTag_2019#5]
Is the dataset used in this project the same as the dataset used in the paper(《Scaling Up Open Tagging from Tens to Thousands: ComprehensionEmpowered Attribute Value Extraction from Product Title》)? If not, what is the source of this dataset?

**Comment by hackerxiaobai** [comment]
> Is the dataset used in this project the same as the dataset used in the paper(《Scaling Up Open Tagging from Tens to Thousands: ComprehensionEmpowered Attribute Value Extraction from Product Title》)? If not, what is the source of this dataset?

不是，这个数据是我们自己爬的。原论文的数据集我也不知道到哪里找

**Comment by w-zm** [comment]
> > Is the dataset used in this project the same as the dataset used in the paper(《Scaling Up Open Tagging from Tens to Thousands: ComprehensionEmpowered Attribute Value Extraction from Product Title》)? If not, what is the source of this dataset?
> 
> 不是，这个数据是我们自己爬的。原论文的数据集我也不知道到哪里找

好的，谢谢您，我还想问一下这是爬取的哪个电商网站的数据？
