### ISSUE TITLE
What torchcrf is required?

### ISSUE THREAD

**Issue by mechanicpanic** [hackerxiaobai/OpenTag_2019#8]
I have found three packages under that name., and with all three of them I have run into problems. Would it be possible for to tell me which exact package I need to run the code, including the version?

**Comment by wandugu** [comment]
Excuse me, I also encountered the same problem. Has your problem been solved?

**Comment by mechanicpanic** [comment]
Yes, I've used `pip install pytorch-crf` with torch=1.8.1
